[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_ENV = "development"
  CI = "true"

[[redirects]]
  from = "/api/*"
  to = "http://universities.hipolabs.com/:splat"
  status = 200
  force = true
  proxy = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
